// autogenerated by clasp-openvr: do not edit


#include <vulkan/vulkan.h>
#include <vulkan/vulkan_core.h>
#include <clasp/core/foundation.h>
#include <clasp/core/common.h>
#include <clasp/clasp.h>
#include <clasp/clbind/clbind.h>
#include <clasp/clbind/details.h>
#include <clasp/clbind/function.h>
#include <clasp/core/numbers.h>
#include <clasp/core/debugger.h>
#include <clasp/core/array.h>
#include <clasp/core/package.h>
#include <clasp/core/translators.h>
#include <clasp/core/cons.h>
#include "openvr.h"

void startup(){
using namespace clbind;
package("CLASP-OPENVR") [ 
def("VR_Init",&vr::VR_Init,policies<>(),"(peError eApplicationType)"),
def("VR_Shutdown",&vr::VR_Shutdown,policies<>(),"()"),
class_<vr::IVRSpatialAnchors>("vr::IVRSpatialAnchors",no_default_constructor)
.def("CreateSpatialAnchorFromDescriptor",&vr::IVRSpatialAnchors::CreateSpatialAnchorFromDescriptor,policies<>(),"(self pchDescriptor pHandleOut)")
.def("CreateSpatialAnchorFromPose",&vr::IVRSpatialAnchors::CreateSpatialAnchorFromPose,policies<>(),"(self unDeviceIndex eOrigin pPose pHandleOut)")
.def("GetSpatialAnchorPose",&vr::IVRSpatialAnchors::GetSpatialAnchorPose,policies<>(),"(self unHandle eOrigin pPoseOut)")
.def("GetSpatialAnchorDescriptor",&vr::IVRSpatialAnchors::GetSpatialAnchorDescriptor,policies<>(),"(self unHandle pchDescriptorOut punDescriptorBufferLenInOut)")
]; 
};



CLASP_REGISTER_STARTUP(startup);



// end of file
